#------------------------------------------------------------------------------
#Katerina Chinnappan - kachinna
# Makefile for CMPS 109 Programming Project
#
#       make                   makes Main
#------------------------------------------------------------------------------
GPP = g++ -std=c++11
CFLAGS = -g -Wall

TARGET = Main

all: $(TARGET)

$(TARGET): $(TARGET).cpp
	$(GPP) $(CFLAGS) -o $(TARGET) $(TARGET).cpp

clean:
	$(RM) $(TARGET)

	
